### ISSUE TITLE
Support opening playlist files

### ISSUE THREAD

**Issue by pxia** [vitorgalvao/mpv-dummy#1]
I've always wanted a feature for mpv to support opening playlist files without typing them out in the command line. Do you think this script should support checking the file extension, if it's something like `.mpvplaylist` then open with `mpv --playlist` instead of `mpv`?

**Comment by vitorgalvao** [comment]
> Do you think this script should support checking the file extension

Nope, I will specifically not go that route. I want the script to be simple. Checking file extensions is not a reliable way to determine file format.

> if it's something like `.mpvplaylist`

I’ve found no information on that file format.

> then open with `mpv --playlist` instead of `mpv`?

That shouldn’t be necessary, mpv can take a standard playlist file, like `.m3u` and read it directly.

Strangely, it works if I call the script directly but not via Open With. If someone figures out the edits necessary (e.g. to the Info.plist) to make that work, I’ll review and consider adding them, otherwise it’s not something I intend on looking into. This app was born over several tries over different approaches to get something I was happy with, and finally this is it. It’s a project I give out for free to anyone who wants to use it as well, but I don’t intend to spend free time to support and add new features to it if I don’t use them myself. Though again, suggestions with working code will be looked at and possibly implemented.

**Comment by pxia** [comment]
Fair enough. For clarification, I'm not talking about HLS stream's playlist file. `mpv --playlist` can open a text file with filenames on each line. `.mpvplaylist` is just an extension I made up.
