### ISSUE TITLE
Please publish source code for establishing security and trust

### ISSUE THREAD

**Issue by porg** [vitorgalvao/mpv-dummy#3]
1. Thanks for providing this wrapper.

2. I shared it on [apple.stackexchange.com](https://apple.stackexchange.com/questions/413546/installing-homebrew-app-on-m1/473136#473136)

3. Fellow StackExchange user [@Deltics](https://apple.stackexchange.com/users/378728/deltics) commented:

> Useful. But, if you are the author, you should publish the source so that people can be sure that it does (only) what the documentation says it does. The fact that such a simple app doesn't disclose the source is suspicious (perhaps unnecessarily so). If nothing else, without source, it is not possible to say whether the mpv-dummy Automator script would also be vulnerable to a change in the installed location of a brew-managed mpv; if so, then it introduces an additional dependency requiring that "app" to be updated, rather than being able to directly update an Automator script.

In that spirit, as long as there's no official mpv Apple Silicon (ARM) build, and your `mpv-dummy` fills that void (thanks!), it could add some extra trust/transparency if you published your source code in your GitHub repository too.

**Comment by vitorgalvao** [comment]
Thank you for caring and asking.

First, a bit of background: I’ve been working on open-source software for over a decade, including on [Homebrew](https://github.com/Homebrew/brew#who-we-are) (see “Former maintainers with significant contributions”) where I was the longest active maintainer on Homebrew Cask. I continue to contribute to open-source on a nearly daily basis, mostly on Alfred workflows with often hundreds or thousands of users. I care deeply for privacy, security, and correctness, and I think my track record shows that.

So why then isn’t the source for this available? Well, it is. *The app is the source.* As explained in the README, this is just an Automator script compiled as an app[^1] which I then *heavily edited by hand*. That includes adding the icons and painstakingly tweaking the `Info.plist` in a text editor. So there isn’t any other source to share, you see how the app is built by looking at the app. If I added anything to the repo, it would just be the same app that is in the releases.

Ultimately, I’ve built this *for myself* after years of frustration with the situation and I’m sharing it because I know others (including fellow Homebrew maintainers) have the same problem. This is one of those projects where the necessity has outweighed the fun long ago[^2], so if it works for other people that’s great but I truly wouldn’t care if I were the sole user. [An app can be a home cooked meal.](https://www.robinsloan.com/notes/home-cooked-app/) As [explained in another issue](https://github.com/vitorgalvao/mpv-dummy/issues/1#issuecomment-1420002144):

> This app was born over several tries over different approaches to get something I was happy with, and finally this is it. It’s a project I give out for free to anyone who wants to use it as well, but I don’t intend to spend free time to support and add new features to it if I don’t use them myself. Though again, suggestions with working code will be looked at and possibly implemented.

I don’t even promote the app, everyone who found it has done so organically. That’s OK with me. I don’t mind other people sharing the app if they find it useful, but I’m not actively seeking users. I’ve been an open-source maintainer long enough to know that only means more work.

I hope that clarified everything to your satisfaction, though [perhaps I could’ve made it shorter](https://quoteinvestigator.com/2012/04/28/shorter-letter/). Again, thank you for opening the issue and explaining your reasoning clearly and respectfully. Major thumbs up.

One final note: I have thought of remaking this from Xcode and if I ever do it’s likely I’ll publish that, but zero promises of when or even if that’ll happen, per the reasons above. Remaking a working app is quite far down on the list of priorities.

[^1]: Open the `document.wflow` inside the bundle in a text editor and search for `COMMAND_STRING` to see the full three lines of code.

[^2]: I have tried so many approaches over the years.

**Comment by porg** [comment]
Thanks for taking the time to reply!

Inspecting `mpv-dummy.app` with the QuickLook plugin [Apparency](https://www.mothersruin.com/software/Apparency/) shows you have an Apple Developer ID & signed the app:

![mpv-dummy--app-security-info](https://github.com/vitorgalvao/mpv-dummy/assets/737143/ea114288-a0c1-4733-8c1e-7d4cf9b9e7b7)

- This means, that you have undergone the default scrutiny/vetting for 3rd party apps on the Mac platform, which to me is trustworthy enough.
- And after your explanation even further.
- But with great skepticism one will want to see the full source code.
- And with full skepticism even that is not enough, because the binary shipped may not come from the source claimed for, so only building yourself from inspected source code, it the ultimate thing. But who has the time/skillset for this?
- To me with my limited skillset in this domain your app seems overall ok.
- Thank you for providing this dummy!

**Comment by porg** [comment]
## Building an Automator app yourself, pros/cons
- **Pro**: You can trust the integrity of the app.
- **Same**: Base functionality to open the backend mpv for the given file(s).
- **Same**: That annoying "script running" indicator in the menu bar. But I care little b/c mostly I watch videos fullscreen.
- **Con**: You don't get full file type associations in the manifest file `/Applications/mpv.app/Contents/Info.plist`.
- **Con**: Less suited for sharing with friends as one itself may not have an developer ID and code signing capabilities.
